### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by C4ROTTE** [FutureX-Corporate/Futurdustry-Mod#3]
Hello, when i reload mods, a message say some files are missing. I put screenshot of messages here.
![Screenshot_20200514-121846_Mindustry](https://user-images.githubusercontent.com/63516029/81923140-7c10ac80-95dd-11ea-9a36-ec62767d34f2.jpg)
![Screenshot_20200514-121841_Mindustry](https://user-images.githubusercontent.com/63516029/81923158-816df700-95dd-11ea-8404-d679695d5262.jpg)
![Screenshot_20200514-121902_Mindustry](https://user-images.githubusercontent.com/63516029/81923174-86cb4180-95dd-11ea-986d-04c780198433.jpg)
![Screenshot_20200514-121855_Mindustry](https://user-images.githubusercontent.com/63516029/81923191-8c288c00-95dd-11ea-9318-6a0439c48fb7.jpg)
![Screenshot_20200514-121907_Mindustry](https://user-images.githubusercontent.com/63516029/81923202-90ed4000-95dd-11ea-9b50-39b5ea43efa5.jpg)

**Comment by NewJumper** [comment]
I'm still working on the mod, it's not fully done. I've just been so caught
up with school work, that I haven't been able to work on lately.

**Comment by NewJumper** [comment]
I've fixed all these errors you have mentioned above.
:)
