### ISSUE TITLE
A little error

### ISSUE THREAD

**Issue by C4ROTTE** [FutureX-Corporate/Futurdustry-Mod#4]
Hello again, i want try your mod but i have a message who say something missing. I put the screenshot here :)

![Screenshot_20200624-085745_Mindustry](https://user-images.githubusercontent.com/63516029/85511552-04c93200-b5f9-11ea-8ef2-33e85369c676.jpg)

**Comment by matt847** [comment]
Me too

**Comment by NewJumper** [comment]
I'm currently working on. Thanks for reporting! :)

>

**Comment by NewJumper** [comment]
working on it*

>

**Comment by matt847** [comment]
Please let me know when It 's finish

Il gio 2 lug 2020, 21:37 NewJumper <notifications@github.com> ha scritto:

**Comment by NewJumper** [comment]
Alright
